name: test, build and deploy workflow
on: 
    push:
        branches: main
jobs:
    test:
        runs-on: ubuntu-latest    
        steps: 
         - name: Get Code from repo
           uses: actions/checkout@v4    
         - name: Find manage.py file
           run: cat manage.py
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}         
