name: test, build and deploy workflow
on: 
    push:
        branches: main
jobs:
    test:
        runs-on: ubuntu-latest    
        steps: 
         - name: Get Code from repo
           uses: actions/checkout@v4    
         - name: Find manage.py file
           run: cat manage.py
    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Get Code from repo
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}       
            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                context: .
                push: true
                tags: tayo9/recipeapp-django 
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: us-east-1    
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }} 
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
          
            - name: Pull Docker image
              run: docker pull ${{ secrets.DOCKER_USERNAME }}/recipeapp-django       

