name: test, build and deploy workflow
on: 
    push:
        branches: main
jobs:
    test:
        runs-on: ubuntu-latest    
        steps: 
         - name: Find manage.py file
           run: cat manage.py  
