name: test, build and deploy workflow
on: 
    push:
        branches: main
jobs:
    test:
        runs-on: ubuntu-latest    
        steps: 
         - name: Get Code from repo
           uses: actions/checkout@v4    
         - name: Find manage.py file
           run: cat manage.py
    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Get Code from repo
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}       
            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                context: .
                push: true
                tags: tayo9/recipeapp-django 
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.5.4
              with:
                ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}
            - name: Run SSH command
              run: |
                  ssh -o StrictHostKeyChecking=no ubuntu@ec2-44-222-227-27.compute-1.amazonaws.com 'docker compose pull && docker compose up --force-recreate -d'    